services:
  postgres:
    image: postgres:18
    container_name: game_library_db
    environment:
      POSTGRES_DB: game_library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: